In [ ]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])
a
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(f"a[0]:", a[0])
print(f"a[1]:", a[1])
print(f"a[2]:", a[2])
print(f"a[3]:", a[3])
print(f"a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [6]:
print(np.__version__)

2.3.2


In [7]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('<U21')

In [12]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b

array([  3.1 ,  11.02,   6.2 , 213.2 ,   5.2 ])

In [13]:
type(b)

numpy.ndarray

In [14]:
b.dtype

dtype('float64')

In [ ]:
c = np.array([20, 1, 3, 6, 6])
c

array([20,  1,  3,  6,  6])

In [16]:
type(c)

numpy.ndarray

In [17]:
c.dtype

dtype('int64')

In [18]:
c[0] = 100
c

array([100,   1,   3,   6])

In [21]:
c[4] = 0
c

array([20,  1,  3,  6,  0])

In [ ]:
a = np.array([10, 2, 11, 40, 50])
a[0] = 11
a[2] = 20
a

array([11,  2, 20, 40, 50])

In [32]:
d = c[1:4]
d

array([1, 3, 6])

In [ ]:
c[3:5] = 300, 400
c

array([ 20,   1,   3, 300, 400])

In [ ]:
arr = np.array([1, 2, 34, 5, 6, 7])

print(arr[1:5:2])

[2 5]


In [35]:
print(arr[:4])

[ 1  2 34  5]


In [36]:
print(arr[4:])

[6 7]


In [37]:
print(arr[1:5:])

[ 2 34  5  6]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
print(arr[1::2])

[2 4 6 8]


In [49]:
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [52]:
c = np.array([20, 1, 2, 3, 5, 7])
d = c[select]
d

array([20,  2,  3,  5])

In [53]:
c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000,      7])

In [54]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [55]:
a.size

5

In [56]:
a.ndim

1

In [57]:
a.shape

(5,)

In [58]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

In [59]:
b.size

7

In [61]:
a = np.array([1, -1, 1, -1])
a

array([ 1, -1,  1, -1])

In [62]:
mean = a.mean()
mean

np.float64(0.0)

In [65]:
standard_deviation = a.std()
standard_deviation

np.float64(1.0)

In [ ]:
b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [68]:
max_b = b.max()
max_b

np.int64(5)

In [69]:
min_b = b.min()
min_b

np.int64(-1)

In [ ]:
c = np.array([-10, 201, 43, 94, 502])
print(c.max())
print(c.min())
print(c.sum())

502
-10
830


In [ ]:
u = np.array([1, 0])
u

array([1, 0])

In [ ]:
v = np.array([0, 1])
v

array([0, 1])

In [ ]:
z = np.add(u, v)
z

array([1, 1])

In [76]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(np.add(arr1, arr2))

[30 32 34 36 38 40]


In [ ]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [78]:
b = np.array([5, 10, 15])
b

array([ 5, 10, 15])

In [ ]:
c = np.subtract(b, a)
c

array([ -5, -10, -15])

In [85]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
print(np.subtract(arr1, arr2))

[-10  -1   8  17  26  35]


In [86]:
# Create a numpy array

x = np.array([1, 2])
x

array([1, 2])

In [87]:
# Create a numpy array

y = np.array([2, 1])
y

array([2, 1])

In [ ]:
z = np.multiply(x, y)
z

array([2, 2])

In [90]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])
print(np.multiply(arr1, arr2))

[ 20  20  60 120 200 300]


In [91]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [92]:
b = np.array([2, 10, 5])
b

array([ 2, 10,  5])

In [93]:
c = np.divide(a, b)
c

array([5., 2., 6.])

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
print(np.divide(arr1, arr2))

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [95]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [96]:
np.dot(X, Y)

np.int64(7)

In [97]:
print(X[0])
print(X[1])
print(Y[0])
print(Y[1])

1
2
3
2


In [98]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])
print(np.dot(arr1, arr2)) # 6 + 20 = 26

26


In [99]:

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

In [100]:
u + 1

array([2, 3, 4, 0])

In [101]:
arr = np.array([1, 2, 3, -1]) 
arr + 5

array([6, 7, 8, 4])

In [102]:

np.pi

3.141592653589793

In [103]:
x = np.array([0, np.pi/2 , np.pi])
x

array([0.        , 1.57079633, 3.14159265])

In [104]:
y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])